config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#index'

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      post :login
      get :sign_in
    end
  end

  resources :articles, only: [:show, :new, :create]
  resources :comments
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  after_create :update_secret_key

  def update_secret_key
    update_columns(secret_key: Digest::MD5.hexdigest("#{self.id}-#{self.created_at.to_s}"))
  end

  def content_format
    ActionView::Base.full_sanitizer.sanitize(content)
  end

  def picture_url
    c = content.match(/\/\/[^\s]*(jpg|gif|png)/)
    c.present? ? c.to_s : nil
  end
end

# == Schema Information
#
# Table name: articles
#
#  id            :bigint(8)        not null, primary key
#  comment_count :integer          default(0)
#  content       :text
#  like_count    :integer          default(0)
#  title         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :bigint(8)
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find_by(secret_key: params[:id])
    @comments = @article.comments

    if current_user
      @comment = Comment.new
    end
  end

  def new
    @article = Article.new
  end
  
  def create 
    @article = Article.new(article_params)
    if @article.save
      render js: "toastr.success('发表成功！'); window.location.href='/articles/#{@article.secret_key}';"
    else
      render js: "toastr.error('发表失败！')"
    end
  end

  def article_params
    params.require(:article).permit(:title, :content, :user_id)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment.html.erb
<div class="comment-list">
  <% if current_user.nil? %>
    <div>
      <form class="new-comment">
        <a class="avatar">
          <img src="https://cdn2.jianshu.io/assets/default_avatar/avatar_default-78d4d1f68984cd6d4379508dd94b4210.png">
        </a> 
        <div class="sign-container">
          <a href="sessions/sign_in" class="btn btn-sign">登录</a> 
          <span>后发表评论</span>
        </div>
      </form> 
      <!---->
    </div>
  <% else %>
    <div>
      <%= simple_form_for @comment, url: comments_path, method:'post', remote: true do |f| %>
        <%= f.input :article_id, input_html: { value: @article.id}, as: :hidden %>
        <%= f.input :user_id, input_html: { value: current_user.id}, as: :hidden %>
        <%= f.input :content, placeholder: '写下你的评论...', as: :text, label: false %>
        <%= f.button :submit, value: '发表', class: 'btn btn-lg btn-primary btn-block' %>
      <% end %>

    </div>
  <% end %>
  <div class="featured-comment-list">
    <div class="top-title">
      <span><%= @article.comment_count %>条评论</span>
    </div>
      
    <% @comments.each do |comment| %>
      <div class="comment">
        <div class="author">
          <div class="v-tooltip-container" style="z-index: 0;">
            <div class="v-tooltip-content">
              <div class="avatar">
                <img src="https://cdn2.jianshu.io/assets/default_avatar/avatar_default-78d4d1f68984cd6d4379508dd94b4210.png">
              </div>  
            </div> 
          </div>
          <div class="info">
            <div class="name"><%= comment.user&.name %></div>
            <div class="meta">
              <span> <%= comment.created_at.to_s(:db) %></span>
            </div>
          </div> 
          
        </div>

        <div class="comment-wrap">
          <p>
            <%= comment.content %>
          </p>
        </div>

      </div>
    <% end %>
  </div>


</div>

app/views/articles/new.html.erb
<script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=nd5jlirnq6dknmrsuoerfohbgn6kxeggmpqhd3eclgp3j26t"></script>

<div class="new_article">
  
  <%= simple_form_for @article, url: articles_path, method:'post', remote: true do |f| %>
    <%= f.input :user_id, input_html: { value: current_user.id}, as: :hidden %>
    <%= f.input :title, placeholder: '标题', label: '标题' %>
    <%= f.input :content, as: :text, label: false %>
    <%= f.button :submit, value: '发表', class: 'btn btn-lg btn-primary btn-block' %>
  <% end %>

</div>

<script type="text/javascript">
  tinymce.init({selector: '#article_content'});
</script>

app/views/articles/show.html.erb
<div class="note" >
  <% if @article.blank? %>
    <h6> 可能是因为您的链接地址有误、该文章已经被作者删除或转为私密状态。 </h6>
  <% else %>
  <div class="article">
    <h1 class="title"><%= @article.title %> </h1>
    <div class="author">
      <div class="info">
        <span class="name"><%= @article.user.name %></span>
        <!-- 文章数据信息 -->
        <div class="meta">
          <!-- 如果文章更新时间大于发布时间，那么使用 tooltip 显示更新时间 -->
          <span class="publish-time"><%= @article.created_at.to_s(:db) %></span>
          <span class="wordage">字数 <%= @article.content_format.size %></span>
          <span class="comments-count">评论 <%= @article.comment_count %></span>
          <span class="likes-count">喜欢 <%= @article.like_count %></span>
        </div>
      </div>
    </div>

    <div data-note-content="" class="show-content">
      <p>
        <%= @article.content.html_safe %>
      </p>
    </div>
  </div>

  <%= render "comment" %>

  <% end %>
</div>