config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#index'

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      post :login
      get :sign_in
    end
  end

  resources :articles, only: [:show, :new, :create]
  resources :comments
end

app/views/layouts/_header.html.erb
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=" <%= root_path%> ">BLOG</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href=" <%= root_path%> ">首页</a></li>
            <li><a href="#">关于</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.present? %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> 
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="#"></a>我的主页</li>
                  <li><a href="#">设置</a></li>
                  <li><a href="#">登录记录</a></li>
                  <li>
                    <a data-confirm="确定退出?" data-method="delete" href="/sessions/destroy">退出</a>
                  </li>

                </ul>
              </li>
              <li><a href=" <%= new_article_path %>">写文章</a></li>
            <% else %>
              <li><a href=<%= sign_in_sessions_path%> >登录</a></li>
              <li><a href=<%= new_session_path%> >注册</a></li>
            <% end %>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>部落格</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>